mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    # ex: /polls/    
    path('', views.index, name="index"),
    # ex: /polls/5
    path('<int:question_id>/', views.detail, name="detail"),
    # ex: /polls/5/results
    path('<int:question_id>/results/', views.results, name="results"),
    # ex: /polls/5/vote
    path('<int:question_id>/vote/', views.vote, name="vote"),
]

mysite/polls/models.py
import datetime


from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")


    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    

    def __str__(self):
        return f"{self.question_text} published on {self.pub_date}"


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


    def __str__(self):
        return f"{self.choice_text} for question {self.question} and has vote{self.votes}"

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.db.models import F


from .models import Choice, Question


def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)        
    return render(request, "polls/default.html", {"question": question})



def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


# ...
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/vote.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

mysite/polls/templates/polls/default.html
<!-- <h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in  question.choice_set.all %}
        <li>
            {{ choice.choice_text }}
        </li>
    {% endfor %}
</ul> -->

mysite/polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Document</title>
    <style>
        /* styles.css */
body {
    font-family: 'Arial', sans-serif;
    background-color: #f0f0f0;
}

.container {
    margin-top: 20px;
}

ul {
    list-style-type: none;
    padding: 0;
}

li {
    margin-bottom: 10px;
    transition: transform 0.3s ease-in-out;
}

li:hover {
    transform: scale(1.1);
}

fieldset {
    border: 1px solid #ddd;
    padding: 10px;
    transition: transform 0.3s ease-in-out;
}

fieldset:hover {
    transform: scale(1.1);
}

legend {
    font-size: 24px;
    font-weight: bold;
}

input[type="submit"] {
    background-color: #007bff;
    color: #fff;
    padding: 10px 20px;
    border: none;
    cursor: pointer;
    transition: background-color 0.3s ease-in-out;
}

input[type="submit"]:hover {
    background-color: #0056b3;
}

a {
    color: #007bff;
    text-decoration: none;
    margin-right: 20px;
    transition: color 0.3s ease-in-out;
}

a:hover {
    color: #0056b3;
}


.custom-box {
    background-color: #fff;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    padding: 20px;
    border-radius: 10px;
    animation: fadeInUp 0.5s ease; /* Add fade-in animation */
}

@keyframes fadeInUp {
    from {
        opacity: 0;
        transform: translateY(20px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}

    </style>
</head>
<body>
<div class="container">
<div class="row mt-5 flex justify-content-center">
<div class="col-12 custom-box" >
{% if latest_question_list %}
<ul>
{% for question in latest_question_list %}
    <!-- <li><a href="/polls/{{ question.id }}/">{{question.question_text}}</a></li> -->
    <li><a href="{% url 'polls:vote' question.id %}">{{question.question_text}}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
</div>
</div>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <div><a href="{% url 'polls:vote' question.id %}">Vote again?</a></div>
    <div><a href="{% url 'polls:index' %}">Go to the home page</a></div>
    
</body>
</html>

mysite/polls/templates/polls/vote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vote</title>
</head>
<body>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
        </form>
        <a href="{% url 'polls:index' %}">Go to the home page</a>

</body>
</html>